/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package setup;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JLabel;

/**
 *
 * @author metes
 */
public class Greetings extends javax.swing.JFrame {

    /**
     * Creates new form Greetings
     */
    Extract extract;
    public Greetings() {
        initComponents();
        
    }
    public void setExtract(Extract extract){
        this.extract=extract;
    }
    public void setLeftComponent(){
        
        
     jLabel1.setIcon(new javax.swing.ImageIcon(extract.getLeftImage()));
        try {
            this.setIconImage(ImageIO.read(new ByteArrayInputStream(extract.getIconImage())));
        } catch (IOException ex) {
            Logger.getLogger(Greetings.class.getName()).log(Level.SEVERE, null, ex);
        }
     setTitle(getTitle()+extract.getName());
       
    }
    
    public void setBottomComponent(javax.swing.JComponent jComponent){
        jPanel2.add(jComponent);
        jPanel2.repaint();
       
    }
    public void myInit(){
        setSize(R.WINDOW_WIDTH,R.WINDOW_HEIGHT);
        setPreferredSize(R.WINDOW_WIDTH,R.WINDOW_HEIGHT);
        setVisible(true);
        setEnabled(true);
        
        int y=(int) (R.WINDOW_HEIGHT/1.25);
        int x=(int) (R.WINDOW_WIDTH/3.1);
        this.setLocation((R.WIDTH-R.WINDOW_WIDTH)/2, (R.HEIGHT-R.WINDOW_HEIGHT)/2);
        jPanel1.setBounds(0, 0, x,y);
        jLabel1.setBounds(0, 0, x,y);
        jPanel2.setBounds(0, y, R.WINDOW_WIDTH, R.WINDOW_HEIGHT-y-30);
        jPanel3.setBounds(x, 0, R.WINDOW_WIDTH-x, R.WINDOW_HEIGHT-jPanel2.getHeight()-32);
        setLeftComponent();
        //pack();
    }
    public int bPanelHeight(){
        return jPanel2.getHeight();
    }
    public Extract getExtract(){
        return extract;
    }
    public Rectangle getMiddleBounds(){
            return jPanel3.getBounds();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Setup -");
        setPreferredSize(new java.awt.Dimension(300, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setPreferredSize(jPanel1.getSize());
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 0, 0);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(227, 5, 0, 0);

        jPanel2.setBackground(new java.awt.Color(200, 200, 200));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(null);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(232, 5, 0, 0);

        jPanel3.setBackground(new java.awt.Color(235, 235, 235));
        jPanel3.setLayout(null);
        getContentPane().add(jPanel3);
        jPanel3.setBounds(260, 90, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Greetings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Greetings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Greetings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Greetings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Greetings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    void setPreferredSize(int WINDOW_WIDTH, int WINDOW_HEIGHT) {
        setPreferredSize(new Dimension(WINDOW_WIDTH,WINDOW_HEIGHT));
    }

    void setMiddleComponent(javax.swing.JComponent myl) {
          jPanel3.add(myl);
          jPanel3.repaint();
    }
}
