/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package setup;

import java.awt.Color;
import java.awt.Dimension;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author metes
 */
public class Inters extends javax.swing.JFrame {

    /**
     * Creates new form Inters
     */
    Extract extract;
    public Inters() {
        initComponents();
    }
    public void setExtract(Extract extract){
        this.extract=extract;
    }
    public void setLeftComponent(){
        
        
     jLabel1.setIcon(new javax.swing.ImageIcon(extract.getIconImage()));
        try {
            this.setIconImage(ImageIO.read(new ByteArrayInputStream(extract.getIconImage())));
        } catch (IOException ex) {
            Logger.getLogger(Greetings.class.getName()).log(Level.SEVERE, null, ex);
        }
     setTitle(getTitle()+extract.getName());
       
    }
    public void myInit(){
        setSize(R.WINDOW_WIDTH,R.WINDOW_HEIGHT);
        setPreferredSize(new Dimension(R.WINDOW_WIDTH,R.WINDOW_HEIGHT));
        setVisible(true);
        setEnabled(true);
        int y=(int) (R.WINDOW_HEIGHT/1.25);
        int x=(int) (R.WINDOW_WIDTH/3.1);
        this.setLocation((R.WIDTH-R.WINDOW_WIDTH)/2, (R.HEIGHT-R.WINDOW_HEIGHT)/2);
        setLeftComponent();
        jPanel1.setBounds(-5, -5, R.WINDOW_WIDTH+5, (int)(R.WINDOW_HEIGHT/5.7));
            jLabel1.setBounds(R.WINDOW_WIDTH-R.WINDOW_WIDTH/7, 10, R.WINDOW_WIDTH-100, 50);
            jLabel2.setLocation(30, 10);
            jLabel2.setText("License Agreement");
            jLabel3.setBounds(R.WINDOW_WIDTH-R.WINDOW_WIDTH/7, 10, R.WINDOW_WIDTH-100, 50);
            jLabel3.setLocation(40, 15);
            jLabel3.setText("Please read the following important information before continuing.");
       // jPanel1.setBackground(Color.red);
        jPanel1.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Setup -");
        setPreferredSize(new java.awt.Dimension(300, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 5));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setup/icon.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 34, 14);

        jLabel2.setBackground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("Label 2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 10, 150, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 70, 30, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 10, 380, 140);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 170, 100, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
